### ISSUE TITLE
Is this completed?

### ISSUE THREAD

**Issue by rwerthman** [streed/simpleRaft#8]
Hello,

I have a few questions.

I was wondering if this the raft algorithm was fully implemented in this?

Do you have any reference implementations for this?

I am supposed to download a raft implementation for my Distributed Systems class and add some more functionality. I'm trying to find a working implementation in python and this looks fairly good.

**Comment by streed** [comment]
The algorithm itself is completed. It is missing features such as log compaction, but the core is there. As for communication and the like there is a zeroRPC ability that someone fixed, but I have not gotten around to ensuring that it works.

**Comment by rwerthman** [comment]
Ok, thanks!  One more thing, are you able to provide some kind of reference implementation.  Maybe where you create 2 servers, there is an election, and there is a client that sends a command to the servers.  That command is then replicated in the logs.  This doesn't have to be with zeroRPC, just in-memory objects created in a main method communicating with eachother.

**Comment by ongardie** [comment]
@horatiusMMXIV, what class? I'm trying to list them on https://raft.github.io/#courses . Would appreciate a PR there if yours isn't listed.

**Comment by rwerthman** [comment]
It is csci 5673 Distributed Systems at University of Colorado Boulder.
